on:
  push:
    branches:
      - master

env:
  TF_VAR_SLACK_INCOMING_WEBHOOK_01: ${{ secrets.SLACK_INCOMING_WEBHOOK_01 }}
  TF_VAR_SLACK_INCOMING_WEBHOOK_02: ${{ secrets.SLACK_INCOMING_WEBHOOK_02 }}
  TMP_AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_ARN_GITHUB_ACTIONS_ADMINISTRATOR }}
          aws-region: ap-northeast-1
      - run: terraform init
      - run: terraform apply -auto-approve
      - run: terraform output
